openapi: 3.0.0
info:
  title: Parameterized Builds API
  description: >
    Rest Api for handling data stored by the Parameter Builds
    for Jenkins plugin
  version: 1.0

paths:
  /global/servers:
    get:
      summary: Get global jenkins servers
      description: >
        Returns a list of jenkins servers defined in the
        global admin settings. Default user token ommitted
        for security.
      responses:
        '200':
          description: A JSON array of server objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Server'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Unexpected'
  
  /projects/{projectKey}/servers:
    get:
      summary: Get project-level jenkins servers
      description: >
        Returns a list of jenkins servers defined in the
        project admin settings. Default user token ommitted
        for security.
      parameters:
        - name: projectKey
          in: path
          description: unique key for given project
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A JSON array of server objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Server'
        '404':
          description: Project not found
        '403':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Unexpected'


components:
  schemas:
    Server:
      type: object
      properties:
        url:
          type: string
        alias:
          type: string
        scope:
          type: string
          enum: [global, project]
        project:
          type: string
        default_user:
          type: string
        root_token_enabled:
          type: boolean
        csrf_enabled:
          type: boolean
      required:
        - url
        - alias
        - scope
        - root_token_enabled
        - csrf_enabled
  
  responses:
    Unauthorized:
      description: Unauthorized
    Unexpected:
      description: Unexpected error

