openapi: "3.0.0"
info:
  title: Parameterized Builds API
  description: >
    Rest Api for handling data stored by the Parameter Builds
    for Jenkins plugin
  version: "1.0"

paths:
  /global/servers:
    get:
      summary: Get global jenkins servers
      description: >
        Returns a list of jenkins servers defined in the
        global admin settings. Default user token omitted
        for security.
      responses:
        '200':
          description: A JSON array of server objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Server'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Unexpected'

  /global/servers/validate:
    post:
      summary: Test server settings
      description: >
        Check if the given jenkins settings can successfully
        send a post request to the jenkins server.
      responses:
        '200':
          description: Connection successful
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Connection test failed
          content:
            application/json:
              schema:
                type: string
        '403':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Unexpected'

  /global/servers/{serverAlias}:
    put:
      summary: Create or update a server
      description: >
        Creates or updates a server in the global settings
        for the given serverAlias. As of now, only one
        server per scope is supported so any existing
        global server will be replaced with this server.
      parameters:
        - name: serverAlias
          in: path
          description: Server Nickname
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Server updated
        '201':
          description: Server created
        '403':
          $ref: '#/components/responses/Unauthorized'
        '422':
          $ref: '#/components/responses/BadInput'
        '5XX':
          $ref: '#/components/responses/Unexpected'
    delete:
      summary: Remove a server
      description: >
        Remove the server with the given alias from the
        global settings. Since only one server is supported
        currently, this will simply remove the global server
        regardless of the serverAlias provided.
      parameters:
        - name: serverAlias
          in: path
          description: Server Nickname
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Server removed
        '403':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Unexpected'

  /global/servers/{serverAlias}/userToken:
    put:
      summary: Set user token for jenkins server
      description: >
        Sets the authenticated user's token for the jenkins
        server defined at serverAlias in the global jenkins
        settings. If no token is defined, the current user
        token is removed.
      parameters:
        - name: serverAlias
          in: path
          description: Server Nickname
          required: true
          schema:
            type: string
        - name: toke
          in: body
          required: false
          schema:
            type: string
      responses:
        '204':
          description: Token updated
        '403':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Unexpected'
    delete:
      summary: Remove user token for given jenkins server
      description: >
        Removes the authenticated user's api token for
        the given jenkins server.
      parameters:
        - name: serverAlias
          in: path
          description: Server Nickname
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Token removed
        '403':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Unexpected'

  /projects/{projectKey}/servers:
    get:
      summary: Get project-level jenkins servers
      description: >
        Returns a list of jenkins servers defined in the
        project admin settings. Default user token omitted
        for security.
      parameters:
        - name: projectKey
          in: path
          description: unique key for given project
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A JSON array of server objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Server'
        '404':
          description: Project not found
        '403':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Unexpected'

  /projects/{projectKey}/servers/validate:
    post:
      summary: Test server settings
      description: >
        Check if the given jenkins settings can successfully
        send a post request to the jenkins server.
      parameters:
        - name: projectKey
          in: path
          description: unique key for given project
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Connection successful
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Connection test failed
          content:
            application/json:
              schema:
                type: string
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Project not found
        '5XX':
          $ref: '#/components/responses/Unexpected'

  /projects/{projectKey}/servers/{serverAlias}:
    put:
      summary: Create or update a server
      description: >
        Creates or updates a server in the given project's
        settings for the given serverAlias. As of now, only one
        server per scope is supported so any existing
        project server will be replaced with this server.
      parameters:
        - name: projectKey
          in: path
          description: unique key for given project
          required: true
          schema:
            type: string
        - name: serverAlias
          in: path
          description: Server Nickname
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Server updated
        '201':
          description: Server created
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Project not found
        '422':
          $ref: '#/components/responses/BadInput'
        '5XX':
          $ref: '#/components/responses/Unexpected'
    delete:
      summary: Remove a server
      description: >
        Remove the server with the given alias from the
        project's settings. Since only one server is supported
        currently, this will simply remove the project's server
        regardless of the serverAlias provided.
      parameters:
        - name: projectKey
          in: path
          description: unique key for given project
          required: true
          schema:
            type: string
        - name: serverAlias
          in: path
          description: Server Nickname
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Server removed
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Project not found
        '5XX':
          $ref: '#/components/responses/Unexpected'

  /projects/{projectKey}/servers/{serverAlias}/userToken:
    put:
      summary: Set user token for jenkins server
      description: >
        Sets the authenticated user's token for the jenkins
        server defined at serverAlias in the project's jenkins
        settings. If no token is defined, the current user
        token is removed.
      parameters:
        - name: projectKey
          in: path
          description: unique key for given project
          required: true
          schema:
            type: string
        - name: serverAlias
          in: path
          description: Server Nickname
          required: true
          schema:
            type: string
        - name: toke
          in: body
          required: false
          schema:
            type: string
      responses:
        '204':
          description: Token updated
        '403':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Unexpected'
    delete:
      summary: Remove user token for given jenkins server
      description: >
        Removes the authenticated user's api token for
        the given jenkins server.
      parameters:
        - name: projectKey
          in: path
          description: unique key for given project
          required: true
          schema:
            type: string
        - name: serverAlias
          in: path
          description: Server Nickname
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Token removed
        '403':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Unexpected'

  /projects/{projectKey}/repos/{repositorySlug}/jobs:
    get:
      summary: Get defined jobs for repository
      description: Returns a list of jobs defined in the repository settings.
      parameters:
        - name: projectKey
          in: path
          description: unique key for given project
          required: true
          schema:
            type: string
        - name: repositorySlug
          in: path
          description: unique (for project) key for given repository
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A JSON array of job objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
        '404':
          description: Project or repository not found
        '403':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Unexpected'

  /projects/{projectKey}/repos/{repositorySlug}/jobs/{id}:
    get:
      summary: Get defined job for repository
      description: Returns a job defined in the repository settings for the given id.
      parameters:
        - name: projectKey
          in: path
          description: unique key for given project
          required: true
          schema:
            type: string
        - name: repositorySlug
          in: path
          description: unique (for project) key for given repository
          required: true
          schema:
            type: string
        - name: id
          in: path
          description: job id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A JSON job object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '404':
          description: Project/repository/job not found
        '403':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Unexpected'
    put:
      summary: Create or update a job
      description: >
        Creates or updates a job in the given repository's
        settings for the given id.
      parameters:
        - name: projectKey
          in: path
          description: unique key for given project
          required: true
          schema:
            type: string
        - name: repositorySlug
          in: path
          description: unique (for project) key for given repository
          required: true
          schema:
            type: string
        - name: id
          in: path
          description: job id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Job'
      responses:
        '200':
          description: Job updated
        '201':
          description: Job created
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Project or repository not found
        '422':
          $ref: '#/components/responses/BadInput'
        '5XX':
          $ref: '#/components/responses/Unexpected'
    delete:
      summary: Remove a job
      description: >
        Remove the job with the given id from the
        repository settings.
      parameters:
        - name: projectKey
          in: path
          description: unique key for given project
          required: true
          schema:
            type: string
        - name: repositorySlug
          in: path
          description: unique (for project) key for given repository
          required: true
          schema:
            type: string
        - name: id
          in: path
          description: job id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Job removed
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Project/repository/job not found
        '5XX':
          $ref: '#/components/responses/Unexpected'

components:
  schemas:
    Server:
      type: object
      properties:
        url:
          type: string
        alias:
          type: string
        scope:
          type: string
          enum: [global, project]
        project:
          type: string
        default_user:
          type: string
        root_token_enabled:
          type: boolean
        csrf_enabled:
          type: boolean
      required:
        - url
        - alias
        - scope
        - root_token_enabled
        - csrf_enabled
    Job:
      type: object
      properties:
        id:
          type: string
        job_name:
          type: string
          description: Job Name
        jenkins_server:
          type: string
          description: Jenkins Server
        is_tag:
          type: boolean
          description: 'Ref type: true - tag, false - branch'
        is_pipeline:
          type: boolean
          description: Multibranch Pipeline
        triggers:
          type: array
          description: Triggers
          items:
            type: string
            enum:
              - 'add'
              - 'push'
              - 'manual'
              - 'delete'
              - 'prautomerged'
              - 'propened'
              - 'prreopened'
              - 'prsourcerescoped'
              - 'prdestrescoped'
              - 'prmerged'
              - 'prdeclined'
              - 'prdeleted'
              - 'prapproved'
          uniqueItems: true
          minItems: 1
        token:
          type: string
          description: Trigger builds remotely (e.g., from scripts) or leave blank to use user API token
        build_parameters:
          type: array
          description: >
            Available Bitbucket variables: $BRANCH, $COMMIT, $REPOSITORY, $PROJECT, $TRIGGER
            (for PR triggers also $PRID, $PRTITLE, $PRDESTINATION, $PRAUTHOR, $PREMAIL,
              $PRDESCRIPTION, $PRURL, $PRSOURCEPROJECT, $PRSOURCEREPOSITORY, and for PR MERGED triggers $MERGECOMMIT))
          items:
            type: object
            properties:
              name:
                type: string
              value:
                type: string
                description: For choice parameters separate values with a semicolon.
        branch_regex:
          type: string
          description: >
            Trigger builds for matched branches or tags (example: "release.*|hotfix.*|production").
            Supported triggers: REF CREATED, PUSH EVENT, REF DELETED
        path_regex:
          type: string
          description: >
            Trigger builds if matched files are modified (example: "directory/.*.txt|foobar/.*").
            Supported triggers:
              PUSH EVENT, PR OPENED, PR REOPENED, PR SOURCE RESCOPED, PR DEST RESCOPED, PR MERGED, PR DECLINED, PR DELETED
        require_permission:
          type: string
          description: Only allow users with the given repository permission or higher to trigger this job.
          enum:
            - 'REPO_READ'
            - 'REPO_WRITE'
            - 'REPO_ADMIN'
        pr_destination_regex:
          type: string
          description: >
            Trigger builds if the pull request destination matches the regex (example: "release.*|hotfix.*|production").
            Supported triggers: PR OPENED, PR REOPENED, PR SOURCE RESCOPED, PR DEST RESCOPED, PR MERGED, PR DECLINED, PR DELETED
      required:
        - id
        - job_name
        - jenkins_server
        - triggers
      example:
        id: '0'
        job_name: 'Update Satis Package'
        jenkins_server: 'Platform'
        is_tag: true
        triggers:
          - add
          - delete
          - prautomerged
          - push
          - prmerged
        token: '__JENKINS_TOKEN__'
        build_parameters:
          - name: VENDOR
            value: $PROJECT
          - name: PACKAGE
            value: $REPOSITORY
        branch_regex: ''
        path_regex: ''
        require_permission: 'REPO_READ'
        pr_destination_regex: ''

  responses:
    Unauthorized:
      description: Unauthorized
    Unexpected:
      description: Unexpected error
    BadInput:
      description: Request body rejected
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  type: string
            required:
              - errors
